'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property acquisitiontype() As DbSet(Of acquisitiontype)
    Public Overridable Property aws_elements() As DbSet(Of aws_elements)
    Public Overridable Property aws_stations() As DbSet(Of aws_stations)
    Public Overridable Property climsoftusers() As DbSet(Of climsoftusers)
    Public Overridable Property data_forms() As DbSet(Of data_forms)
    Public Overridable Property flags() As DbSet(Of flags)
    Public Overridable Property form_daily2() As DbSet(Of form_daily2)
    Public Overridable Property form_hourly() As DbSet(Of form_hourly)
    Public Overridable Property form_hourly_time_selection() As DbSet(Of form_hourly_time_selection)
    Public Overridable Property form_hourlywind() As DbSet(Of form_hourlywind)
    Public Overridable Property form_synoptic_2_ra1() As DbSet(Of form_synoptic_2_ra1)
    Public Overridable Property form_synoptic2_tdcf() As DbSet(Of form_synoptic2_tdcf)
    Public Overridable Property instrument() As DbSet(Of instrument)
    Public Overridable Property instrumentfaultreport() As DbSet(Of instrumentfaultreport)
    Public Overridable Property language_translation() As DbSet(Of language_translation)
    Public Overridable Property obselement() As DbSet(Of obselement)
    Public Overridable Property obsscheduleclass() As DbSet(Of obsscheduleclass)
    Public Overridable Property paperarchivedefinition() As DbSet(Of paperarchivedefinition)
    Public Overridable Property physicalfeatureclass() As DbSet(Of physicalfeatureclass)
    Public Overridable Property qc_interelement_1() As DbSet(Of qc_interelement_1)
    Public Overridable Property qc_interelement_2() As DbSet(Of qc_interelement_2)
    Public Overridable Property qc_interelement_relationship_definition() As DbSet(Of qc_interelement_relationship_definition)
    Public Overridable Property qcstatusdefinition() As DbSet(Of qcstatusdefinition)
    Public Overridable Property qctype() As DbSet(Of qctype)
    Public Overridable Property regkeys() As DbSet(Of regkeys)
    Public Overridable Property routinereportdefinition() As DbSet(Of routinereportdefinition)
    Public Overridable Property seq_daily_element() As DbSet(Of seq_daily_element)
    Public Overridable Property seq_element() As DbSet(Of seq_element)
    Public Overridable Property seq_month_day() As DbSet(Of seq_month_day)
    Public Overridable Property seq_month_day_leap_yr() As DbSet(Of seq_month_day_leap_yr)
    Public Overridable Property seq_month_day_synoptime() As DbSet(Of seq_month_day_synoptime)
    Public Overridable Property seq_month_day_synoptime_leap_yr() As DbSet(Of seq_month_day_synoptime_leap_yr)
    Public Overridable Property station() As DbSet(Of station)
    Public Overridable Property stationnetworkdefinition() As DbSet(Of stationnetworkdefinition)
    Public Overridable Property synopfeature() As DbSet(Of synopfeature)
    Public Overridable Property tblproducts() As DbSet(Of tblproducts)
    Public Overridable Property featuregeographicalposition() As DbSet(Of featuregeographicalposition)
    Public Overridable Property observationfinal() As DbSet(Of observationfinal)
    Public Overridable Property observationinitial() As DbSet(Of observationinitial)
    Public Overridable Property physicalfeature() As DbSet(Of physicalfeature)
    Public Overridable Property seq_month_day_element() As DbSet(Of seq_month_day_element)
    Public Overridable Property seq_month_day_element_leap_yr() As DbSet(Of seq_month_day_element_leap_yr)

End Class
